package client;

import common.Task;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

public class CreateTaskView {
    private JPanel createPanel;
    JLabel descriptionLabel = new JLabel("Description:");
    JLabel priorityLabel = new JLabel("Priority:");
    JTextField descriptionText = new JTextField();
    JTextField priorityText = new JTextField();
    JButton saveButton = new JButton("Create");

    public CreateTaskView() {
        createPanel.setLayout(new GridLayout(0, 1));
        createPanel.setSize(new Dimension(300, 300));
        createPanel.add(descriptionLabel);
        createPanel.add(descriptionText);
        createPanel.add(priorityLabel);
        createPanel.add(priorityText);
        createPanel.add(saveButton);
        display();

        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                Task newCreatedTask = new Task();
                newCreatedTask.setDescription(descriptionText.getText());
                newCreatedTask.setPriority(Integer.valueOf(priorityText.getText()));
                try {
                    ClientSocketOpenedHandler.postTaskOnServer(newCreatedTask);
                    Client.createTaskView.getCreatePanel().setVisible(false);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    public void display() {
        if (Client.editTaskView != null) {
            Client.editTaskView.getEditPanel().setVisible(false);
        }
        descriptionText.setText("");
        priorityText.setText("");

        getCreatePanel().setVisible(true);
    }

    public JPanel getCreatePanel() {
        return createPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createPanel = new JPanel();
        createPanel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return createPanel;
    }

}
